version: "3.9"
services:
  api:
    build:
      context: ./backend/src/LotterySystem.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=lottery_db;Username=postgres;Password=postgres
      Jwt__Issuer: LotterySystem
      Jwt__Audience: LotterySystem.Client
      Jwt__Key: CHANGE_ME_TO_A_LONG_SECURE_SECRET_KEY
    depends_on:
      - db
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: lottery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
